<a href="https://colab.research.google.com/github/micaeljin/neural-networks-zero-to-hero/blob/main/build_makemore_mlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt


In [3]:
words = open('/names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [4]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [8]:
block_size = 3
X, Y = [], []

for w in words[:5]:
  print(w)
  context = [0] * block_size

  for ch in w + '.':
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
ava
... ---> a
..a ---> v
.av ---> a
ava ---> .
isabella
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
sophia
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .


In [9]:
X.shape,  Y.shape

(torch.Size([32, 3]), torch.Size([32]))

In [10]:
X, Y

(tensor([[ 0,  0,  0],
         [ 0,  0,  5],
         [ 0,  5, 13],
         [ 5, 13, 13],
         [13, 13,  1],
         [ 0,  0,  0],
         [ 0,  0, 15],
         [ 0, 15, 12],
         [15, 12,  9],
         [12,  9, 22],
         [ 9, 22,  9],
         [22,  9,  1],
         [ 0,  0,  0],
         [ 0,  0,  1],
         [ 0,  1, 22],
         [ 1, 22,  1],
         [ 0,  0,  0],
         [ 0,  0,  9],
         [ 0,  9, 19],
         [ 9, 19,  1],
         [19,  1,  2],
         [ 1,  2,  5],
         [ 2,  5, 12],
         [ 5, 12, 12],
         [12, 12,  1],
         [ 0,  0,  0],
         [ 0,  0, 19],
         [ 0, 19, 15],
         [19, 15, 16],
         [15, 16,  8],
         [16,  8,  9],
         [ 8,  9,  1]]),
 tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
          1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0]))

In [13]:
C = torch.randn((27, 2))

In [14]:
C[5]

tensor([ 1.6281, -0.4564])

In [16]:
F.one_hot(torch.tensor(5), num_classes=27).float() @ C

tensor([ 1.6281, -0.4564])

In [17]:
C

tensor([[-0.0102,  1.3065],
        [ 0.4305,  0.7857],
        [ 0.9071,  0.5717],
        [ 0.7452, -1.4809],
        [-1.0424,  1.1710],
        [ 1.6281, -0.4564],
        [ 0.4500, -1.6398],
        [-1.9689, -0.1376],
        [ 0.8145,  0.5319],
        [ 0.6852, -2.3316],
        [-0.0091,  0.7332],
        [ 1.1701, -1.6782],
        [-0.7602,  0.5941],
        [-0.0413,  0.9530],
        [ 0.2586, -0.6210],
        [-0.1048,  0.3733],
        [ 0.5230,  2.3651],
        [ 0.9812, -0.9340],
        [ 0.0527, -0.0925],
        [-0.4792,  0.2055],
        [-0.7010, -0.6531],
        [-0.6580, -0.3703],
        [-0.7331,  1.4627],
        [-1.3077, -0.3385],
        [-0.5310,  0.1791],
        [-0.3693,  0.5137],
        [ 1.9534, -0.2899]])

In [18]:
C[[1, 2, 3]]

tensor([[ 0.4305,  0.7857],
        [ 0.9071,  0.5717],
        [ 0.7452, -1.4809]])

In [19]:
C[X]

tensor([[[-0.0102,  1.3065],
         [-0.0102,  1.3065],
         [-0.0102,  1.3065]],

        [[-0.0102,  1.3065],
         [-0.0102,  1.3065],
         [ 1.6281, -0.4564]],

        [[-0.0102,  1.3065],
         [ 1.6281, -0.4564],
         [-0.0413,  0.9530]],

        [[ 1.6281, -0.4564],
         [-0.0413,  0.9530],
         [-0.0413,  0.9530]],

        [[-0.0413,  0.9530],
         [-0.0413,  0.9530],
         [ 0.4305,  0.7857]],

        [[-0.0102,  1.3065],
         [-0.0102,  1.3065],
         [-0.0102,  1.3065]],

        [[-0.0102,  1.3065],
         [-0.0102,  1.3065],
         [-0.1048,  0.3733]],

        [[-0.0102,  1.3065],
         [-0.1048,  0.3733],
         [-0.7602,  0.5941]],

        [[-0.1048,  0.3733],
         [-0.7602,  0.5941],
         [ 0.6852, -2.3316]],

        [[-0.7602,  0.5941],
         [ 0.6852, -2.3316],
         [-0.7331,  1.4627]],

        [[ 0.6852, -2.3316],
         [-0.7331,  1.4627],
         [ 0.6852, -2.3316]],

        [[-0.7331,  1

In [20]:
C[X].shape

torch.Size([32, 3, 2])

In [21]:
C[X][13, 2]

tensor([0.4305, 0.7857])

In [22]:
C[1]

tensor([0.4305, 0.7857])

In [23]:


emb = C[X]
emb.shape

torch.Size([32, 3, 2])

In [24]:
W1 = torch.randn((6, 100))
b1 = torch.randn(100)


In [27]:
torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]], 1).shape

torch.Size([32, 6])

In [29]:
torch.cat(torch.unbind(emb, 1), 1).shape

torch.Size([32, 6])

In [34]:
h = torch.tanh(emb.view(-1, 6) @ W1 + b1)

In [35]:
h

tensor([[-0.1932,  0.9957, -0.9997,  ...,  0.9949, -0.9827,  0.8778],
        [-0.9881,  0.8114, -0.9991,  ...,  0.9997,  0.9777, -0.9724],
        [ 0.9821,  0.9995, -0.9912,  ..., -0.9158,  0.8195,  0.9203],
        ...,
        [-0.9798,  0.6195, -1.0000,  ...,  0.9993, -0.8980, -0.6787],
        [-0.6733,  0.8757,  0.5290,  ...,  1.0000,  0.9999, -1.0000],
        [ 0.9138,  0.9966, -0.4226,  ..., -1.0000,  0.9654,  0.9544]])

In [36]:
h.shape

torch.Size([32, 100])

In [38]:
W2 = torch.randn((100, 27))
b2 = torch.rand(27)

logits = h @ W2 + b2

In [39]:
logits.shape

torch.Size([32, 27])

In [40]:
counts = logits.exp()

In [41]:
prob = counts / counts.sum(1, keepdims=True)

In [42]:
prob.shape

torch.Size([32, 27])

In [46]:
prob[torch.arange(32), Y]

tensor([4.2880e-03, 9.2221e-06, 4.0266e-08, 5.6923e-06, 1.2663e-08, 3.7377e-06,
        1.9317e-11, 1.2207e-07, 2.0830e-04, 8.5327e-04, 2.3284e-15, 4.2237e-12,
        1.0065e-05, 2.0512e-15, 1.1852e-02, 6.9134e-07, 3.7106e-07, 4.2854e-16,
        1.7905e-05, 1.9974e-02, 8.7738e-15, 7.2763e-06, 3.2604e-05, 1.5804e-05,
        6.2062e-09, 9.3189e-08, 2.2135e-07, 1.1444e-07, 8.2053e-14, 9.1280e-14,
        3.7085e-16, 1.3173e-06])

In [47]:
loss = -prob[torch.arange(32), Y].log().mean()
loss

tensor(17.5948)